# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bbranch < Formula
  desc "CLI tool for creating Git branches across multiple Bitbucket repos"
  homepage "https://github.com/chinhstringee/bbranch"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chinhstringee/bbranch/releases/download/v0.4.1/bbranch_0.4.1_darwin_amd64.tar.gz"
      sha256 "00a4267e732f2b619f82a0fcb9053c1cd7626ef8545d019dafa814d9450a6137"

      define_method(:install) do
        bin.install "bbranch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chinhstringee/bbranch/releases/download/v0.4.1/bbranch_0.4.1_darwin_arm64.tar.gz"
      sha256 "304c2a2bb1403e5b0e5d0adde46fc31e73a92c9d63405d651d8435963b900178"

      define_method(:install) do
        bin.install "bbranch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinhstringee/bbranch/releases/download/v0.4.1/bbranch_0.4.1_linux_amd64.tar.gz"
      sha256 "217c14cb8308d17daab1e698473b47398ae49995e04a92d1108ad12399b5b22b"
      define_method(:install) do
        bin.install "bbranch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinhstringee/bbranch/releases/download/v0.4.1/bbranch_0.4.1_linux_arm64.tar.gz"
      sha256 "574e1c08d660d11e58406a4644880ebddf438e81cab1e6be9c31edae9d9329f2"
      define_method(:install) do
        bin.install "bbranch"
      end
    end
  end
end
