# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bbranch < Formula
  desc "Multi-repo orchestration tool for Bitbucket"
  homepage "https://github.com/chinhstringee/buck"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chinhstringee/bbranch/releases/download/v0.6.0/bbranch_0.6.0_darwin_amd64.tar.gz"
      sha256 "6314ae9c50ca73d926b0773e3f012f513343a00224102854cd06887e247b7b53"

      define_method(:install) do
        bin.install "buck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chinhstringee/bbranch/releases/download/v0.6.0/bbranch_0.6.0_darwin_arm64.tar.gz"
      sha256 "f745c0c7a2bd06649903e282352e06d86becf69ea244ff66a20dde0bb621f5a5"

      define_method(:install) do
        bin.install "buck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinhstringee/bbranch/releases/download/v0.6.0/bbranch_0.6.0_linux_amd64.tar.gz"
      sha256 "d18deaf47e5f52c162c03234ecc57d12d1e4ec0efb5db9e576698312b58331ae"
      define_method(:install) do
        bin.install "buck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinhstringee/bbranch/releases/download/v0.6.0/bbranch_0.6.0_linux_arm64.tar.gz"
      sha256 "61061a7f9fed59f6ebed715c9437a9c341dde499ef4bbdc311fdf3527894651a"
      define_method(:install) do
        bin.install "buck"
      end
    end
  end
end
