# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Buck < Formula
  desc "Multi-repo orchestration tool for Bitbucket"
  homepage "https://github.com/chinhstringee/buck"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chinhstringee/buck/releases/download/v0.7.0/buck_0.7.0_darwin_amd64.tar.gz"
      sha256 "9374a8f337868b32ef9d0dc1481fd4f355c995d4ef9e013a01410d60f03313d3"

      define_method(:install) do
        bin.install "buck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chinhstringee/buck/releases/download/v0.7.0/buck_0.7.0_darwin_arm64.tar.gz"
      sha256 "cc1964cf78062a996ff6d0f689ba65bfbc2b6e95be107d1e550bacef2a13596e"

      define_method(:install) do
        bin.install "buck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinhstringee/buck/releases/download/v0.7.0/buck_0.7.0_linux_amd64.tar.gz"
      sha256 "378d7d518cd4419894ec3bb6031a66c9afe0254b8e43d6ce0201aa822ef2b5ec"
      define_method(:install) do
        bin.install "buck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinhstringee/buck/releases/download/v0.7.0/buck_0.7.0_linux_arm64.tar.gz"
      sha256 "45ce38c286011e9608518e5f1984913cd7cd357a5818167c4d7e4555a95fb1f0"
      define_method(:install) do
        bin.install "buck"
      end
    end
  end
end
