# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Buck < Formula
  desc "Multi-repo orchestration tool for Bitbucket"
  homepage "https://github.com/chinhstringee/buck"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chinhstringee/buck/releases/download/v0.9.0/buck_0.9.0_darwin_amd64.tar.gz"
      sha256 "d784d73d829b2396e0b65b0a979edc3b71b88ed7db64d975c42f2cc98895b30f"

      define_method(:install) do
        bin.install "buck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chinhstringee/buck/releases/download/v0.9.0/buck_0.9.0_darwin_arm64.tar.gz"
      sha256 "acf660c231b02ccf03c2c00ea12000aa29f5b102518d2a3519fec71f85e69060"

      define_method(:install) do
        bin.install "buck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinhstringee/buck/releases/download/v0.9.0/buck_0.9.0_linux_amd64.tar.gz"
      sha256 "561ea65437a13062f3ab27cf12f051332ff0ec0923a33849bb0d7e9da2294c01"
      define_method(:install) do
        bin.install "buck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinhstringee/buck/releases/download/v0.9.0/buck_0.9.0_linux_arm64.tar.gz"
      sha256 "1dc5c27c69703841fb2c293b9d6772143fcb76fc4e3d5ecca6697e620dad3c40"
      define_method(:install) do
        bin.install "buck"
      end
    end
  end
end
