# This file was generated by GoReleaser. DO NOT EDIT.
cask "bbranch" do
  name "bbranch"
  desc "CLI tool for creating Git branches across multiple Bitbucket repos"
  homepage "https://github.com/chinhstringee/bbranch"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bbranch"

  on_macos do
    on_intel do
      url "https://github.com/chinhstringee/bbranch/releases/download/v#{version}/bbranch_#{version}_darwin_amd64.tar.gz"
      sha256 "f9fdb8ab25a838d5d55c68b20494366dd3fc0e0465b1ace1ea89e390accd3251"
    end
    on_arm do
      url "https://github.com/chinhstringee/bbranch/releases/download/v#{version}/bbranch_#{version}_darwin_arm64.tar.gz"
      sha256 "44b1e71189960d9c0077f4830f64a144da90d2432d2227f22beed8e2784b2742"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chinhstringee/bbranch/releases/download/v#{version}/bbranch_#{version}_linux_amd64.tar.gz"
      sha256 "2db3be1b242ecd7b82cd0691990d1219ff9c0174f979c0a72470aaaf3f487eda"
    end
    on_arm do
      url "https://github.com/chinhstringee/bbranch/releases/download/v#{version}/bbranch_#{version}_linux_arm64.tar.gz"
      sha256 "1070e08ac74d08e3a85d08a77bdbd1f79fbfc36d9baf320b116a7aaa4e1aa411"
    end
  end

  # No zap stanza required
end
