# This file was generated by GoReleaser. DO NOT EDIT.
cask "bbranch" do
  name "bbranch"
  desc "CLI tool for creating Git branches across multiple Bitbucket repos"
  homepage "https://github.com/chinhstringee/bbranch"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bbranch"

  on_macos do
    on_intel do
      url "https://github.com/chinhstringee/bbranch/releases/download/v#{version}/bbranch_#{version}_darwin_amd64.tar.gz"
      sha256 "c45c9cd9bf3f8b796f2fe71e0204e4348dfa9b5029a7c33a16cd89c63716a899"
    end
    on_arm do
      url "https://github.com/chinhstringee/bbranch/releases/download/v#{version}/bbranch_#{version}_darwin_arm64.tar.gz"
      sha256 "dacce7dac211edcd23cb376eb8631b0dae862f19e5740d0d26820b147b641bd8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chinhstringee/bbranch/releases/download/v#{version}/bbranch_#{version}_linux_amd64.tar.gz"
      sha256 "1e35dca5545bcc22d6598304d110b8d503a82cdf64ec4e5e34bd1bc2b5f9a739"
    end
    on_arm do
      url "https://github.com/chinhstringee/bbranch/releases/download/v#{version}/bbranch_#{version}_linux_arm64.tar.gz"
      sha256 "493b94e09fe45cce36eb098588e0c554cd4d437a40a5a0ec0744877e71e8b360"
    end
  end

  # No zap stanza required
end
